
services:
  scanner:
    image: alpine:latest
    container_name: scanner
    command: >
      sh -c "
      apk add --no-cache nmap nmap-scripts curl &&
      while true; do
        echo '\n\n=== SCAN web ===';
        nmap -Pn web;
        echo '\n--- run curl ---';
        curl -s http://web:5000;
        echo '\n\n=== SCAN internal ===';
        nmap -Pn internal;
        echo '\n--- run curl ---';
        curl -s http://internal:5678;
        sleep 10;
      done
      "
    networks:
      - flatnet

  web:
    build: ./web
    container_name: web
    ports:
      - "8080:5000"
    networks:
      - flatnet

  internal:
    image: hashicorp/http-echo
    container_name: internal
    command:
      - "-text=SECRET_INTERNAL_DATA"
    networks:
      - flatnet

networks:
  flatnet:
